services:
  mysql:
    image: mysql:8.0.40-debian
    container_name: mysql_db
    restart: unless-stopped
    platform: linux/amd64
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      - MYSQL_ROOT_PASSWORD=kerekecske
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: backend
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=kerekecske
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL=${EMAIL}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - RECOMMEND=recommendations
    platform: linux/amd64
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: "wget --spider http://localhost:8080/actuator/health || exit 1"
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s

  recommendations:
    build: ./tfidfApiServer
    container_name: recommendations
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=kerekecske
    platform: linux/amd64
    depends_on:
      backend:
        condition: service_healthy

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - 8080:8080
    platform: linux/amd64
    depends_on:
      backend:
        condition: service_healthy
