spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://localhost:3306/recowrite
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: kerekecske
    hikari:
      maximum-pool-size: 4
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

security:
  jwt:
    secret-key: ${JWT_SECRET}