name: eslint
on: [push]
    # push:
    #   paths:
    #     - 'frontend/**'
    # pull_request:
    #   paths:
    #     - 'frontend/**'
jobs:
    build:
        runs-on: ubuntu-latest
        defaults: 
            run:
                working-directory: ./frontend
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Node.js setup
              uses: actions/setup-node@v2
              with:
                node-version: '18'
                cache: 'npm'
                cache-dependency-path: frontend/package-lock.json

            - name: Install dependencies
              run: npm install

            - name: Run HTML validate
              run: npx html-validate --max-warnings=0 .

            - name: Run ESLint
              run: npx eslint --max-warnings=0 .