name: ruff
on:
  push:
    paths:
      - 'tfidfApiServer/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: ./tfidfApiServer
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Python setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: tfidfApiServer/requirements.txt

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff
        run: ruff check . && ruff fix .